travis:
  secure:
    BINSTAR_TOKEN: gXREIPcv6i5jpV81y/JvDAtW/T6n1YSanMblu2KMfSeeSEV5+3N3noRJDRgxFEa7h6WousesBbWQbxAhdeth36YPapc5XdpQtsZKM0uZS0Xj88m8j65xZJW7v9mI9Z4YBAQlwwJYFrOpvlU3y/Jr9btGbaf+r+m1wglsiOFSyj5zWK1QoD/076U7hdDDMeyvvl0x6FBaxoM86i+nFEIzeYMZu7sO0nHI1qBkkH6Z2rrq1/GfIb7z/uUxgSwZQ4asbw14Zgudh7peLkn7W05TEB3JbqcUfuriGAR4lV6O4O3CJAcP9q+iL6HWCWsa1GEqXIHnChfdNk5FdGTGLJhdkBBpvRA+MjKXKJ5W3YvKz/EMzu1OW+l7/iVBasx8xShV3aDLQUjIhK7FStBwX8LByf7gF2uBtPg9vZl/a9rBV95VWV6lo2t9FUhFhsW1O1xuiN0YFcGyulTIpA8focoY5y1Judmm9cxl58JuMpEZl0pPUfaZ3ZCSHZWDQZCdgXIEgSQkrrvxMNDPR3vbgxXj4QM3yqYweJqkluTpj2B5z9gT7nFa+/5b3nbF+RnQvjYP/3mWS/F/R0Bl6k1PnEUgTh96yQdWij1sXNrVfvzZvSJSQr0qy3msKwtZyhqB8fyhw85z3COscXAzrCrcsWKgGyxPvyQvjl4NGOxOsLZJTCc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
